apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        selector: mongodb
    spec:
      terminationGracePeriodSeconds: 3
      containers:
        - name: mongodb
          image: mongo:5.0.20
          # command:
          # - "mongod"
          # - "--bind_ip_all"
          # - "--replSet"
          # - "koeo_rs"
          resources:
            requests:
              cpu: 200m
              memory: 2000Mi
            limits:
              memory: 2000Mi
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: admin
          volumeMounts:
            - name: koeo-mongodb-data
              mountPath: /data/db
            - name: user-role-config
              mountPath: /docker-entrypoint-initdb.d/init-users-and-roles.js
              subPath: init-users-and-roles.js
      volumes:
        - name: user-role-config
          configMap:
            name: init-users-and-roles-config
  volumeClaimTemplates:
    - metadata:
        name: koeo-mongodb-data
      spec:
        # storageClassName: hostpath
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi